In [ ]:
https://github.com/AnchalGupta-1006/NLP

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
voc_size=10000

onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[1222, 8284, 2391, 621], [1222, 8284, 2391, 8752], [1222, 7915, 2391, 5775], [211, 9895, 904, 1105, 5640], [211, 9895, 904, 1105, 5953], [8566, 1222, 220, 2391, 6062], [5420, 7980, 721, 1105]]


In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1222 8284 2391  621]
 [   0    0    0    0 1222 8284 2391 8752]
 [   0    0    0    0 1222 7915 2391 5775]
 [   0    0    0  211 9895  904 1105 5640]
 [   0    0    0  211 9895  904 1105 5953]
 [   0    0    0 8566 1222  220 2391 6062]
 [   0    0    0    0 5420 7980  721 1105]]


In [ ]:
dim = 10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

[[[ 0.01619675  0.01891741 -0.03725884 -0.03248974  0.02514836
    0.0074867  -0.0218704  -0.03400452  0.01757633  0.02289047]
  [ 0.01619675  0.01891741 -0.03725884 -0.03248974  0.02514836
    0.0074867  -0.0218704  -0.03400452  0.01757633  0.02289047]
  [ 0.01619675  0.01891741 -0.03725884 -0.03248974  0.02514836
    0.0074867  -0.0218704  -0.03400452  0.01757633  0.02289047]
  [ 0.01619675  0.01891741 -0.03725884 -0.03248974  0.02514836
    0.0074867  -0.0218704  -0.03400452  0.01757633  0.02289047]
  [-0.03257527 -0.04485491  0.03312022  0.04985848 -0.0430598
   -0.02148124  0.01729611 -0.00131917  0.0026294  -0.04217364]
  [ 0.03460978 -0.02297816  0.02536063 -0.01589312  0.03495656
    0.02106707  0.04782463 -0.04166014 -0.00932197  0.00456776]
  [ 0.00647665 -0.00947983 -0.04999724 -0.04610962  0.02904809
   -0.02055638  0.04289207  0.00457393 -0.03182437  0.04474643]
  [-0.00550527 -0.04574621  0.02359823  0.02277296  0.02753374
   -0.02835341 -0.00034499 -0.04105695  0.0102990

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 1222, 8284, 2391,  621], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

[[ 0.01619675  0.01891741 -0.03725884 -0.03248974  0.02514836  0.0074867
  -0.0218704  -0.03400452  0.01757633  0.02289047]
 [ 0.01619675  0.01891741 -0.03725884 -0.03248974  0.02514836  0.0074867
  -0.0218704  -0.03400452  0.01757633  0.02289047]
 [ 0.01619675  0.01891741 -0.03725884 -0.03248974  0.02514836  0.0074867
  -0.0218704  -0.03400452  0.01757633  0.02289047]
 [ 0.01619675  0.01891741 -0.03725884 -0.03248974  0.02514836  0.0074867
  -0.0218704  -0.03400452  0.01757633  0.02289047]
 [-0.03257527 -0.04485491  0.03312022  0.04985848 -0.0430598  -0.02148124
   0.01729611 -0.00131917  0.0026294  -0.04217364]
 [ 0.03460978 -0.02297816  0.02536063 -0.01589312  0.03495656  0.02106707
   0.04782463 -0.04166014 -0.00932197  0.00456776]
 [ 0.00647665 -0.00947983 -0.04999724 -0.04610962  0.02904809 -0.02055638
   0.04289207  0.00457393 -0.03182437  0.04474643]
 [-0.00550527 -0.04574621  0.02359823  0.02277296  0.02753374 -0.02835341
  -0.00034499 -0.04105695  0.01029908  0.04596326]]
